peppol:
  outbound:
    errors:
      list:
        - type: UNKNOWN_RECIPIENT
          mask: ".*Identifier .* is not registered in SML.*"

        - type: UNSUPPORTED_DATA_FORMAT
          mask: ".*Combination of receiver.*and document type identifier.*is not supported.*"

        - type: DATA_ERROR
          mask: ".*Your are not allowed to override .* in production mode, makes sure headers match the ones in the document.*"

        - type: RECEIVING_AP_ERROR
          mask: ".*Request failed with rc=50.*"

        - type: RECEIVING_AP_ERROR
          mask: ".*Request failed with rc=40.*"

        - type: RECEIVING_AP_ERROR
          mask: ".*Receiving server does not seem to be running.*"

        - type: RECEIVING_AP_ERROR
          mask: ".*Possible invalid SSL Certificate at the other end.*"

        - type: SECURITY_ERROR
          mask: "Validation of subject principal(CN) failed"

        - type: DOCUMENT_ERROR
          mask: "Empty file .* received by .*"